# Generated by Django 5.2.2 on 2025-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpoint', '0003_car_seller_part_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='users/'),
        ),
    ]
