# Generated by Django 5.2.2 on 2025-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpoint', '0006_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Tunisia', max_length=150),
        ),
    ]
